---
# kind: replicated
replicated_api_version: 2.12.0
name: My Counter App
version: 1.0.0
release_notes: The initial release of my counter application.
properties:
  app_url: https://{{repl ConfigOption "hostname" }}
  logo_url: "https://lh6.ggpht.com/uCS3dvm72krkJPG7aHlipfbBBCJ-hiq3nc9bx5wQVSXsaB2Fv2KuyDm7UU4seGwHVl4=w300"
  console_title: My Counter App Console
backup:
  enabled: true
state:
  ready:
    command: http_status_code
    args:
    - https://{{repl ConfigOption "hostname"}}/assets/bootstrap.min.css
    - "200"
cmds:
- name: host_ip
  cmd: publicip
  args: []

host_requirements:
  replicated_version: ">=2.12.0"


config:
- name: hostname
  title: Hostname
  description: Ensure this domain name is routable on your network.
  items:
  - name: hostname
    title: Hostname
    type: text
    recommended: false
    default: ""
    value_cmd:
      name: host_ip
      value_at: 0
    when: ""
    affix: ""
    required: true
    items: []
- name: ssl
  description: ""
  test_proc:
    display_name: Verify TLS settings
    command: certificate_verify
    timeout: 5
    arg_fields:
    - ssl_cert_file
    - ssl_key_file
    - hostname
  items:
  - name: ssl_key_file
    title: Private Key File
    type: file
    required: true
    affix: left
  - name: ssl_cert_file
    title: Certificate File
    type: file
    required: true
    affix: right
---
# kind: scheduler-kubernetes
apiVersion: v1
kind: Pod
metadata:
    name: just-a-pod-for-now
    labels:
        app: demo
spec:
  contatainers:
      - image: nginx
        ports:
          - containerPort: 80

